const location = {
  lat: "test_lat",
  lng: "test_lng",
  country: "test_country",
  state: "test_state",
  county: "test_county",
  city: "test_city",
  district: "test_district",
  postalCode: "test_postalCode",
  locationImage: "test_locationImage",
};

const imgList = [
  {
    imgKey: 0,
    isLoading: false,
    percentage: 100,
    error: false,
    objectUrl: "test_objectUrl",
    standardUrl: "test_standardUrl",
    thumbnailUrl: "test_thumbnailUrl",
  },
  {
    imgKey: 1,
    isLoading: false,
    percentage: 100,
    error: false,
    objectUrl: "test_objectUrl2",
    standardUrl: "test_standardUrl2",
    thumbnailUrl: "test_thumbnailUrl2",
  },
];

const formData = {
  title: "test_title",
  price: "test_price",
  boardType: "test_boardType",
  condition: "test_condition",
  construction: "test_construction",
  glassing: "test_glassing",
  contour: "test_contour",
  lengthFt: "test_lengthFt",
  lengthIn: "test_lengthIn",
  width: "test_width",
  depth: "test_depth",
  volume: "test_volume",
  shaper: "test_shaper",
  model: "test_model",
  finSystem: "test_finSystem",
  finConfiguration: "test_finConfiguration",
  waveSize: "test_waveSize",
  driveSpeed: "test_driveSpeed",
  paddlePower: "test_paddlePower",
  movability: "test_movability",
};

const expectedState = {
  title: "test_title",
  price: "test_price",
  boardType: "test_boardType",
  condition: "test_condition",
  construction: "test_construction",
  glassing: "test_glassing",
  contour: "test_contour",
  lengthFt: "test_lengthFt",
  lengthIn: "test_lengthIn",
  width: "test_width",
  depth: "test_depth",
  volume: "test_volume",
  shaper: "test_shaper",
  model: "test_model",
  finSystem: "test_finSystem",
  finConfiguration: "test_finConfiguration",
  waveSize: "test_waveSize",
  driveSpeed: "test_driveSpeed",
  paddlePower: "test_paddlePower",
  movability: "test_movability",
  images: [
    {
      standardUrl: "test_standardUrl",
      thumbnailUrl: "test_thumbnailUrl",
    },
    {
      standardUrl: "test_standardUrl2",
      thumbnailUrl: "test_thumbnailUrl2",
    },
  ],
  location: {
    lat: "test_lat",
    lng: "test_lng",
    country: "test_country",
    state: "test_state",
    county: "test_county",
    city: "test_city",
    district: "test_district",
    postalCode: "test_postalCode",
    locationImage: "test_locationImage",
  },
};
