//AUTHENTICATION
export const AUTH_USER = 'AUTH_USER';
export const USER_LOADED = 'USER_LOADED';
export const DEAUTH_USER = 'DEAUTH_USER';

//OVERLAYS
export const TOGGLE_REGISTER = 'TOGGLE_REGISTER';
export const TOGGLE_LOGIN = 'TOGGLE_LOGIN';
