//AUTHENTICATION
export const AUTH_USER = 'AUTH_USER';
export const USER_LOADED = 'USER_LOADED';
export const DEAUTH_USER = 'DEAUTH_USER';

//OVERLAYS
export const TOGGLE_REGISTER = 'TOGGLE_REGISTER';
export const TOGGLE_LOGIN = 'TOGGLE_LOGIN';

//CREATE POST
export const SET_INPUT = 'SET_INPUT';
export const SET_OBJECTURL_URL = 'SET_OBJECTURL_URL';
export const SET_IMG_KEY = 'SET_IMG_KEY';
export const SET_UPLOAD_PERCENTAGE = 'SET_UPLOAD_PERCENTAGE';
export const SET_THUMBNAIL_URL = 'SET_THUMBNAIL_URL';
export const SET_STANDARD_URL = 'SET_STANDARD_URL';
export const DELETE_IMG_PREVIEW = 'DELETE_IMG_PREVIEW';
export const SET_DEFAULT_IMAGE = 'SET_DEFAULT_IMAGE';
export const UPLOAD_ERROR = 'UPLOAD_ERROR';
export const CANCEL_POST = 'CANCEL_POST';
