//AUTHENTICATION
export const AUTH_USER = "AUTH_USER";
export const USER_LOADED = "USER_LOADED";
export const DEAUTH_USER = "DEAUTH_USER";

export const UPDATE_USER_NOTIFICATIONS = "UPDATE_USER_NOTIFICATIONS";
export const DECREASE_MESSAGE_NOTIFICATION = "DECREASE_MESSAGE_NOTIFICATION";
export const FLAG_MESSAGE_AS_READ = "FLAG_MESSAGE_AS_READ";

export const UPDATE_USER_POSTS = "UPDATE_USER_POSTS";
export const UPDATE_USER_FAVORITES_ADD = "UPDATE_USER_FAVORITES_ADD";
export const UPDATE_USER_FAVORITES_REMOVE = "UPDATE_USER_FAVORITES_REMOVE";
export const UPDATE_USER_MESSAGES = "UPDATE_USER_MESSAGES";
export const DELETE_MESSAGE_THREAD = "DELETE_MESSAGE_THREAD";
export const UPDATE_USER_PROFILE_IMAGE = "UPDATE_USER_PROFILE_IMAGE";
export const UPDATE_USER_PROFILEBACKGROUND = "UPDATE_USER_PROFILEBACKGROUND";

export const DELETE_POST = "DELETE_POST";

//TEMPORARY DATA
export const SET_POSTLIST = "SET_POSTLIST";

//OVERLAYS
export const TOGGLE_REGISTER = "TOGGLE_REGISTER";
export const TOGGLE_LOGIN = "TOGGLE_LOGIN";

//CREATE POST
export const SET_INPUT = "SET_INPUT";
export const SET_OBJECTURL_URL = "SET_OBJECTURL_URL";
export const SET_IMG_KEY = "SET_IMG_KEY";
export const SET_UPLOAD_PERCENTAGE = "SET_UPLOAD_PERCENTAGE";
export const SET_THUMBNAIL_URL = "SET_THUMBNAIL_URL";
export const SET_STANDARD_URL = "SET_STANDARD_URL";
export const DELETE_IMG_PREVIEW = "DELETE_IMG_PREVIEW";
export const SET_DEFAULT_IMAGE = "SET_DEFAULT_IMAGE";
export const UPLOAD_ERROR = "UPLOAD_ERROR";
export const CANCEL_POST = "CANCEL_POST";
export const RESET_CREATE_POST_FORM_DATA = "RESET_CREATE_POST_FORM_DATA";

export const EDIT_POST_INSERT_DATA = "EDIT_POST_INSERT_DATA";

//LOCATION SERVICE
export const UPDATE_CURRENT_LOCATION = "UPDATE_CURRENT_LOCATION";
export const TOGGLE_LOCATION_LOADING = "TOGGLE_LOCATION_LOADING";
export const UPDATE_LOCATION_IMAGE = "UPDATE_LOCATION_IMAGE";
export const LOAD_DEFAULT_LOCATION_TO_CURRENT =
  "LOAD_DEFAULT_LOCATION_TO_CURRENT";
export const TOGGLE_MAP_LOADING = "TOGGLE_MAP_LOADING";
export const UPDATE_CURRENT_LOCATION_IP = "UPDATE_CURRENT_LOCATION_IP";
export const TOGGLE_CREATE_POST_LOADING = "TOGGLE_CREATE_POST_LOADING";

//FILTERS
export const UPDATE_SORT = "UPDATE_SORT";
export const TOGGLE_FILTERS = "TOGGLE_FILTERS";
export const CHANGE_LAYOUT = "CHANGE_LAYOUT";

export const UPDATE_PRICE_MAX = "UPDATE_PRICE_MAX";
export const UPDATE_PRICE_MIN = "UPDATE_PRICE_MIN";
export const UPDATE_ANY_PRICE = "UPDATE_ANY_PRICE";

export const UPDATE_CONDITION = "UPDATE_CONDITION";

export const UPDATE_BOARD_TYPE = "UPDATE_BOARD_TYPE";

export const UPDATE_DISTANCE = "UPDATE_DISTANCE";

export const UPDATE_ANY_LENGTH = "UPDATE_ANY_LENGTH";
export const UPDATE_DIMENSIONS_LENGTH_MIN_FT =
  "UPDATE_DIMENSIONS_LENGTH_MIN_FT";
export const UPDATE_DIMENSIONS_LENGTH_MAX_FT =
  "UPDATE_DIMENSIONS_LENGTH_MAX_FT";
export const UPDATE_DIMENSIONS_LENGTH_MIN_IN =
  "UPDATE_DIMENSIONS_LENGTH_MIN_IN";
export const UPDATE_DIMENSIONS_LENGTH_MAX_IN =
  "UPDATE_DIMENSIONS_LENGTH_MAX_IN";
export const UPDATE_ANY_WIDTH = "UPDATE_ANY_WIDTH";
export const UPDATE_DIMENSIONS_WIDTH_MIN = "UPDATE_DIMENSIONS_WIDTH_MIN";
export const UPDATE_DIMENSIONS_WIDTH_MAX = "UPDATE_DIMENSIONS_WIDTH_MAX";
export const UPDATE_ANY_DEPTH = "UPDATE_ANY_DEPTH";
export const UPDATE_DIMENSIONS_DEPTH_MIN = "UPDATE_DIMENSIONS_DEPTH_MIN";
export const UPDATE_DIMENSIONS_DEPTH_MAX = "UPDATE_DIMENSIONS_DEPTH_MAX";
export const UPDATE_ANY_VOLUME = "UPDATE_ANY_VOLUME";
export const UPDATE_DIMENSIONS_VOLUME_MIN = "UPDATE_DIMENSIONS_VOLUME_MIN";
export const UPDATE_DIMENSIONS_VOLUME_MAX = "UPDATE_DIMENSIONS_VOLUME_MAX";

//UTILS
export const ADD_VIEW = "ADD_VIEW";
